language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install pipenv
  - pipenv install --dev
script:
  - isort -rc --check-only myutil/
  - flake8 myutil/
  - PYTHONPATH=$(pwd) pytest tests/
